#!/bin/sh

set -eu

if ! cargo fmt -- --check
then
    echo "There are some code style issues."
    echo "Run \"cargo fmt\" before commit."
    exit 1
fi

if ! cargo clippy --all-targets -- -D warnings
then
    echo "There are some clippy issues."
    exit 1
fi

if ! cargo audit
then
    echo "There are some cargo audit issues."
    echo "Audit issues will *not* block the commit."
fi

exit 0
